const styles = {
  global: "_global_1momg_1",
  scrollable: "_scrollable_1momg_13",
  chatScrollable: "_chatScrollable_1momg_23",
  header: "_header_1momg_116",
  Sheet: "_Sheet_1momg_121",
  fieldFullWidth: "_fieldFullWidth_1momg_128",
  fieldRow: "_fieldRow_1momg_132",
  fieldRowNoSpread: "_fieldRowNoSpread_1momg_138",
  fieldColumn: "_fieldColumn_1momg_144",
  fieldFullColumn: "_fieldFullColumn_1momg_150",
  fieldContainer: "_fieldContainer_1momg_154",
  fieldLabel: "_fieldLabel_1momg_175",
  field: "_field_1momg_128",
  fieldConditions: "_fieldConditions_1momg_186",
  fieldStat: "_fieldStat_1momg_197",
  fieldSmall: "_fieldSmall_1momg_210",
  fieldSmallLong: "_fieldSmallLong_1momg_222",
  fieldStatSmall: "_fieldStatSmall_1momg_234",
  fieldStatContainerSmall: "_fieldStatContainerSmall_1momg_247",
  fieldStatContainerSmallRow: "_fieldStatContainerSmallRow_1momg_260",
  fieldStatContainer: "_fieldStatContainer_1momg_247",
  fieldStatLabel: "_fieldStatLabel_1momg_293",
  statContainer: "_statContainer_1momg_302",
  statButton: "_statButton_1momg_312",
  statDetail: "_statDetail_1momg_326",
  talentCount: "_talentCount_1momg_337",
  chatBox: "_chatBox_1momg_343",
  chatField: "_chatField_1momg_354",
  chatSender: "_chatSender_1momg_366",
  poolField: "_poolField_1momg_372",
  poolButtons: "_poolButtons_1momg_380",
  poolContainer: "_poolContainer_1momg_387",
  rollResult: "_rollResult_1momg_398",
  storyButton: "_storyButton_1momg_405",
  logo: "_logo_1momg_410",
  characterRow: "_characterRow_1momg_414",
  fixedMenu: "_fixedMenu_1momg_421",
  menuButton: "_menuButton_1momg_435",
  menuButtonSelected: "_menuButtonSelected_1momg_441",
  pathList: "_pathList_1momg_449",
  pathItem: "_pathItem_1momg_455",
  chatInputContainer: "_chatInputContainer_1momg_488",
  chatCloseButton: "_chatCloseButton_1momg_493"
};

export default styles;
